# Generated by Django 4.1.1 on 2022-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=255)),
                ('st_location', models.CharField(max_length=255)),
                ('st_Address', models.CharField(max_length=255)),
                ('st_status', models.BooleanField()),
            ],
        ),
    ]
