# Generated by Django 4.1.1 on 2022-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_Id', models.IntegerField()),
                ('sell_name', models.CharField(max_length=255)),
                ('sell_gender', models.CharField(max_length=255)),
                ('sell_Address', models.CharField(max_length=255)),
            ],
        ),
    ]
