# Generated by Django 4.1.1 on 2022-09-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.seller'),
            preserve_default=False,
        ),
    ]
