# Generated by Django 4.1.1 on 2022-09-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_store_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog/app/media/store'),
        ),
    ]
